class Images {
  static const String Intro1 = "assets/images/intro_1.png";
  static const String Intro2 = "assets/images/intro_2.png";
  static const String Intro3 = "assets/images/intro_3.png";
  static const String Logo = "assets/images/logo.png";
  static const String Slide = "assets/images/slide.png";
  static const String Avatar1 = "assets/images/avata-01.jpeg";
  static const String Avatar2 = "assets/images/avata-02.jpeg";
  static const String Avatar3 = "assets/images/avata-03.jpeg";
  static const String Avatar4 = "assets/images/avata-04.png";
  static const String Profile1 = "assets/images/profile-1.jpg";
  static const String Profile2 = "assets/images/profile-2.jpg";
  static const String Profile3 = "assets/images/profile-3.jpg";
  static const String Profile4 = "assets/images/profile-4.jpg";
  static const String Profile5 = "assets/images/profile-5.jpg";
  static const String Profile6 = "assets/images/profile-6.jpg";
  static const String Profile7 = "assets/images/profile-7.jpg";
  static const String Profile8 = "assets/images/profile-8.jpg";
  static const String Trip1 = "assets/images/trip-1.jpg";
  static const String Trip2 = "assets/images/trip-2.jpg";
  static const String Trip3 = "assets/images/trip-3.jpg";
  static const String Trip4 = "assets/images/trip-4.jpg";
  static const String Trip5 = "assets/images/trip-5.jpg";
  static const String Trip6 = "assets/images/trip-6.jpg";
  static const String Trip7 = "assets/images/trip-7.jpg";
  static const String Trip8 = "assets/images/trip-8.jpg";
  static const String Trip9 = "assets/images/trip-9.jpg";
  static const String Room1 = "assets/images/room-1.jpg";
  static const String Room2 = "assets/images/room-2.jpg";
  static const String Room3 = "assets/images/room-3.jpg";
  static const String Room4 = "assets/images/room-4.jpg";
  static const String Room5 = "assets/images/room-5.jpg";
  static const String Room6 = "assets/images/room-6.jpg";
  static const String Room7 = "assets/images/room-7.jpg";
  static const String Room8 = "assets/images/room-8.jpg";
  static const String Room9 = "assets/images/room-9.jpg";
  static const String Room10 = "assets/images/room-10.jpg";
  static const String Room11 = "assets/images/room-11.jpg";
  static const String Banner1 = "assets/images/banner-1.jpg";
  static const String Banner2 = "assets/images/banner-2.jpg";
  static const String Banner3 = "assets/images/banner-3.jpg";
  static const String Category1 = "assets/images/category-1.jpg";
  static const String Category2 = "assets/images/category-2.jpg";
  static const String Category3 = "assets/images/category-3.jpg";
  static const String Category4 = "assets/images/category-4.jpg";
  static const String Gallery1 = "assets/images/gallery-1.jpg";
  static const String Gallery2 = "assets/images/gallery-2.jpg";
  static const String Location1 = "assets/images/location-1.jpg";
  static const String Location2 = "assets/images/location-2.jpg";
  static const String Location3 = "assets/images/location-3.jpg";
  static const String Location4 = "assets/images/location-4.jpg";
  static const String Location5 = "assets/images/location-5.jpg";
  static const String Location6 = "assets/images/location-6.jpg";
  static const String Location7 = "assets/images/location-7.jpg";
  static const String Location8 = "assets/images/location-8.jpg";
  static const String Location9 = "assets/images/location-9.jpg";
  static const String Location10 = "assets/images/location-10.jpg";
  static const String Location11 = "assets/images/location-11.jpg";
  static const String Location12 = "assets/images/location-12.jpg";
  static const String Location13 = "assets/images/location-13.jpg";
  static const String Location14 = "assets/images/location-14.jpg";
  static const String RealEstate1 = "assets/images/real-estate-1.jpg";
  static const String RealEstate2 = "assets/images/real-estate-2.jpg";
  static const String RealEstate3 = "assets/images/real-estate-3.jpg";
  static const String RealEstate4 = "assets/images/real-estate-4.jpg";
  static const String RealEstate5 = "assets/images/real-estate-5.jpg";
  static const String RealEstate6 = "assets/images/real-estate-6.jpg";
  static const String RealEstate7 = "assets/images/real-estate-7.jpg";
  static const String RealEstate8 = "assets/images/real-estate-8.jpg";
  static const String Event1 = "assets/images/event-1.jpg";
  static const String Event2 = "assets/images/event-2.jpg";
  static const String Event3 = "assets/images/event-3.jpg";
  static const String Event4 = "assets/images/event-4.jpg";
  static const String Event5 = "assets/images/event-5.jpg";
  static const String Event6 = "assets/images/event-6.jpg";
  static const String Event7 = "assets/images/event-7.jpg";
  static const String Event8 = "assets/images/event-8.jpg";
  static const String Event9 = "assets/images/event-9.jpg";
  static const String Food1 = "assets/images/food-1.jpg";
  static const String Food2 = "assets/images/food-2.jpg";
  static const String Food3 = "assets/images/food-3.jpg";
  static const String Food4 = "assets/images/food-4.jpg";
  static const String Food5 = "assets/images/food-5.jpg";
  static const String Food6 = "assets/images/food-6.jpg";
  static const String Food7 = "assets/images/food-7.jpg";
  static const String Food8 = "assets/images/food-8.jpg";
  static const String Place1 = "assets/images/place-1.jpg";
  static const String Place2 = "assets/images/place-2.jpg";
  static const String Service1 = "assets/images/service-shopping.jpg";
  static const String Service2 = "assets/images/service-automotive.jpg";
  static const String Service3 = "assets/images/service-coffee.jpg";
  static const String Service4 = "assets/images/service-event.jpg";
  static const String Service5 = "assets/images/service-housing.jpg";
  static const String Service6 = "assets/images/service-job.jpg";
  static const String Service7 = "assets/images/service-restaurant.jpg";

  ///Singleton factory
  static final Images _instance = Images._internal();

  factory Images() {
    return _instance;
  }

  Images._internal();
}
